migasfree/server/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.views.generic import RedirectView, TemplateView
from django.urls import reverse_lazy
from django.conf import settings

from .views import *

public_patterns = [
    url(r'repository-url-template/', RepositoriesUrlTemplateView.as_view()),  # valid until migasfree-client 4.16
    url(r'server/info/', ServerInfoView.as_view()),
]

urlpatterns = [
    url(r'^src/', get_source_file, name='get_source_file'),

    url(r'^accounts/login/$', login, name='login'),

    url(
        r'^$',
        TemplateView.as_view(template_name='welcome.html'),
        name='bootstrap'
    ),

    url(
        r'^favicon\.ico$',
        RedirectView.as_view(
            url='%simg/favicon.png' % settings.STATIC_URL
        ),
    ),

    url(r'^api/v1/public/', include(public_patterns)),

    url(r'^query/(?P<query_id>\d+)/$', get_query, name='query'),
    url(
        r'^computer/messages/$',
        computer_messages,
        name='computer_messages'
    ),

    url(r'^info/(.*)', info, name='package_info'),

    url(
        r'^computer/(?P<pk>\d+)/hardware/$',
        hardware_resume,
        name='hardware_resume'
    ),
    url(
        r'^hw-node/(?P<pk>\d+)/$',
        hardware_extract,
        name='hardware_extract'
    ),

    url(
        r'^admin/server/computer/change_status/$',
        computer_change_status,
        name='computer_change_status'
    ),

    url(
        r'^admin/server/computer/delete_selected/$',
        computer_delete_selected,
        name='computer_delete_selected'
    ),

    url(
        r'^admin/server/computer/(?P<pk>\d+)/delete/$',
        ComputerDelete.as_view(),
        name='computer_delete'
    ),

    url(
        r'^admin/server/platform/delete_selected/$',
        platform_delete_selected,
        name='platform_delete_selected'
    ),

    url(
        r'^admin/server/platform/(?P<pk>\d+)/delete/$',
        PlatformDelete.as_view(),
        name='platform_delete'
    ),

    url(
        r'^admin/server/project/(?P<pk>\d+)/delete/$',
        ProjectDelete.as_view(),
        name='project_delete'
    ),

    url(r'^api/$', api, name='api'),

    url(
        r'^get_projects/$',
        get_projects,
        name='get_projects'
    ),
    url(
        r'^get_computer_info/$',
        get_computer_info,
        name='get_computer_info'
    ),
    url(
        r'^computer/(?P<uuid>.+)/label/$',
        computer_label,
        name='computer_label',
    ),
    url(
        r'^get_key_repositories/$',
        get_key_repositories,
        name='get_key_repositories'
    ),
    url(
        r'^timeline/$',
        timeline,
        name='timeline',
    ),
    url(
        r'^connections_model/$',
        connections_model,
        name='connections_model'
    ),

    url(
        r'^computer/replacement/$',
        computer_replacement,
        name='computer_replacement'
    ),

    url(
        r'^computer/(?P<pk>\d+)/events/$',
        computer_events,
        name='computer_events',
    ),

    url(
        r'^computer/(?P<pk>\d+)/simulate/$',
        computer_simulate_sync,
        name='computer_simulate_sync',
    ),

    url(
        r'^link/$',
        link,
        name='link',
    ),

    url(
        r'^device/replacement/$',
        device_replacement,
        name='device_replacement'
    ),

    url(
        r'^computer_autocomplete/$',
        ComputerAutocomplete.as_view(),
        name='computer_autocomplete',
    ),

    url(
        r'^attribute_autocomplete/$',
        AttributeAutocomplete.as_view(),
        name='attribute_autocomplete',
    ),

    url(
        r'^device_autocomplete/$',
        DeviceAutocomplete.as_view(),
        name='device_autocomplete',
    ),

    url(
        r'^user_profile_autocomplete/$',
        UserProfileAutocomplete.as_view(),
        name='user_profile_autocomplete',
    ),

    url(
        r'^group_autocomplete/$',
        GroupAutocomplete.as_view(),
        name='group_autocomplete',
    ),

    url(
        r'^domain_autocomplete/$',
        DomainAutocomplete.as_view(),
        name='domain_autocomplete',
    ),

    url(
        r'^device_connection_autocomplete/$',
        DeviceConnectionAutocomplete.as_view(),
        name='device_connection_autocomplete',
    ),

    url(
        r'^device_model_autocomplete/$',
        DeviceModelAutocomplete.as_view(),
        name='device_model_autocomplete',
    ),

    url(
        r'^device_logical_autocomplete/$',
        DeviceLogicalAutocomplete.as_view(),
        name='device_logical_autocomplete',
    ),

    url(
        r'^domain/change/$',
        change_domain,
        name='change_domain'
    ),

    url(
        r'^scope/change/$',
        change_scope,
        name='change_scope'
    ),

    # backwards compatibility
    url(
        r'^migasfree/$',
        RedirectView.as_view(url=reverse_lazy('bootstrap')),
    ),
    url(
        r'^migasfree/main/$',
        RedirectView.as_view(url=reverse_lazy('bootstrap')),
    ),
    url(r'^status/$', RedirectView.as_view(url=reverse_lazy('bootstrap')),),
    url(r'^migasfree/api/$', api),  # for 2.x clients
    url(
        r'^get_versions/$',
        RedirectView.as_view(url=reverse_lazy('get_projects'))
    ),
    url(
        r'^chart/version_computer/$',
        RedirectView.as_view(url=reverse_lazy('stats_dashboard'))
    ),
    url(
        r'^chart/synchronized_daily/$',
        RedirectView.as_view(url=reverse_lazy('stats_syncs_daily'))
    ),
    url(
        r'^chart/synchronized_monthly/$',
        RedirectView.as_view(url=reverse_lazy('stats_syncs_monthly'))
    ),
    url(
        r'^chart/delay_schedule/$',
        RedirectView.as_view(url=reverse_lazy('stats_project_schedule_delays'))
    ),
    url(
        r'^chart/delay_schedule/(?P<project_name>.+)/$',
        RedirectView.as_view(url=reverse_lazy('stats_project_schedule_delays'))
    ),
    url(
        r'^chart/dashboard/$',
        RedirectView.as_view(url=reverse_lazy('stats_dashboard'))
    ),
    url(
        r'^provided_computers/$',
        RedirectView.as_view(url=reverse_lazy('provided_computers'))
    ),
    url(
        r'^computer_label/$',
        computer_label
    ),
]

migasfree/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

from ajax_select import urls as ajax_select_urls
from rest_framework.authtoken import views
from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view

from server.routers import router, device_router
from catalog.routers import router as catalog_router
from stats.routers import router as stats_router

from django.contrib import admin
admin.autodiscover()

TITLE = 'Migasfree REST API'

swagger_schema_view = get_swagger_view(title=TITLE)

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^docs/', swagger_schema_view, name='docs'),
    url(r'^api-docs/', include_docs_urls(title=TITLE)),
    url(r'^token-auth/$', views.obtain_auth_token),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^api/v1/token/', include(router.urls)),
    url(r'^api/v1/token/', include(stats_router.urls)),
    url(r'^api/v1/token/devices/', include(device_router.urls)),
    url(r'^api/v1/token/catalog/', include(catalog_router.urls)),

    url(r'', include('migasfree.server.urls')),
    url(r'', include('migasfree.stats.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^markdownx/', include('markdownx.urls')),

    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

    if settings.STATIC_ROOT is not None:
        urlpatterns += static(
            settings.STATIC_URL,
            document_root=settings.STATIC_ROOT
        )

    if settings.MEDIA_ROOT is not None:
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
            show_indexes=True
        )

migasfree/server/models/attribute_set.py
# -*- coding: utf-8 -*-

from django.db import models
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db.models.signals import pre_delete, pre_save, m2m_changed
from django.dispatch import receiver

from . import Property, Attribute, MigasLink
from ..utils import sort_depends


class AttributeSetManager(models.Manager):
    def scope(self, user):
        qs = super(AttributeSetManager, self).get_queryset()
        if not user.is_view_all():
            qs = qs.filter(
                included_attributes__in=user.get_attributes()
            ).distinct()

        return qs


@python_2_unicode_compatible
class AttributeSet(models.Model, MigasLink):
    name = models.CharField(
        verbose_name=_("name"),
        max_length=50,
        unique=True
    )

    description = models.TextField(
        verbose_name=_("description"),
        null=True,
        blank=True
    )

    enabled = models.BooleanField(
        verbose_name=_("enabled"),
        default=True,
    )

    included_attributes = models.ManyToManyField(
        Attribute,
        blank=True,
        verbose_name=_("included attributes"),
    )

    excluded_attributes = models.ManyToManyField(
        Attribute,
        related_name="ExcludedAttributesGroup",
        blank=True,
        verbose_name=_("excluded attributes"),
    )

    objects = AttributeSetManager()

    def __str__(self):
        return self.name

    def related_objects(self, model, user):
        """
        Return Queryset with the related computers based in attributes
        """
        from migasfree.server.models import Computer
        if model == 'computer':
            return Computer.productive.scope(user).filter(
                sync_attributes__in=self.included_attributes.all()
            ).exclude(
                sync_attributes__in=self.excluded_attributes.all()
            ).distinct()

        return None

    def clean(self):
        super(AttributeSet, self).clean()

        if self.id:
            att_set = AttributeSet.objects.get(pk=self.id)
            if att_set.name != self.name and \
                    Attribute.objects.filter(
                        property_att=Property.objects.get(prefix='SET', sort='basic'),
                        value=self.name
                    ).exists():
                raise ValidationError(_('Duplicated name'))

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        super(AttributeSet, self).save(force_insert, force_update, using, update_fields)

        Attribute.objects.get_or_create(
            property_att=Property.objects.get(prefix='SET', sort='basic'),
            value=self.name,
            defaults={'description': ''}
        )

    @staticmethod
    def sets_dependencies():
        sets = {}
        for item in AttributeSet.objects.filter(enabled=True):
            sets[item.id] = []

            for subset in item.included_attributes.filter(
                ~Q(value='ALL SYSTEMS')
            ).filter(
                property_att__prefix='SET'
            ).filter(
                ~Q(value=item.name)
            ):
                sets[item.id].append(AttributeSet.objects.get(name=subset.value).id)

            for subset in item.excluded_attributes.filter(
                ~Q(value='ALL SYSTEMS')
            ).filter(
                property_att__prefix='SET'
            ).filter(
                ~Q(value=item.name)
            ):
                sets[item.id].append(AttributeSet.objects.get(name=subset.value).id)

        return sets

    @staticmethod
    def process(attributes):
        property_set = Property.objects.get(prefix='SET', sort='basic')

        depends = AttributeSet.sets_dependencies()
        sets = []
        try:
            sets = sort_depends(depends)
        except ValueError:
            pass

        att_id = []
        for item in sets:
            for att_set in AttributeSet.objects.filter(
                id=item
            ).filter(
                Q(included_attributes__id__in=attributes)
            ).filter(
                ~Q(excluded_attributes__id__in=attributes)
            ).distinct():
                att = Attribute.objects.create(property_set, att_set.name)
                att_id.append(att.id)
                # IMPORTANT: appends attribute to attribute list
                attributes.append(att.id)

        return att_id

    class Meta:
        app_label = 'server'
        verbose_name = _("Attribute Set")
        verbose_name_plural = _("Attribute Sets")
        permissions = (("can_save_attributeset", "Can save Attribute Sets"),)


@receiver(pre_save, sender=AttributeSet)
def pre_save_attribute_set(sender, instance, **kwargs):
    if instance.id:
        att_set = AttributeSet.objects.get(pk=instance.id)
        if instance.name != att_set.name:
            att = Attribute.objects.get(
                property_att=Property.objects.get(prefix='SET', sort='basic'),
                value=att_set.name
            )
            att.update_value(instance.name)


@receiver(pre_delete, sender=AttributeSet)
def pre_delete_attribute_set(sender, instance, **kwargs):
    Attribute.objects.filter(
        property_att=Property.objects.get(prefix='SET', sort='basic'),
        value=instance.name
    ).delete()


@receiver(m2m_changed, sender=AttributeSet.included_attributes.through)
@receiver(m2m_changed, sender=AttributeSet.excluded_attributes.through)
def prevent_circular_dependencies(sender, instance, action, reverse, model, pk_set, **kwargs):
    if action != 'pre_add':
        return

    if not reverse:
        depends = AttributeSet.sets_dependencies()
        atts_id = [int(x) for x in pk_set]
        depends[instance.id] = list(AttributeSet.objects.filter(
            name__in=Attribute.objects.filter(
                id__in=atts_id,
                property_att__prefix='SET'
            ).values_list('value', flat=True)
        ).values_list('id', flat=True))

        try:
            sort_depends(depends)
        except ValueError as e:
            from ast import literal_eval

            depends = literal_eval(str(e))
            if instance.id in depends:
                del depends[instance.id]

            review = list(AttributeSet.objects.filter(
                id__in=list(depends.keys())
            ).values_list('name', flat=True))
            raise ValidationError(_('Review circular dependencies: %s') % ', '.join(review))

migasfree/server/models/autocheck_error.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class AutoCheckError(models.Model):
    """
    This model is used to autocheck the errors and marked as 'checked' when they
    are introducing in the system. Sometimes the Package Management System, in
    the clients, return an error when really it is only a warning.
    The origin of this problem is that the package is poorly packaged.
    """
    message = models.TextField(
        verbose_name=_("message"),
        null=True,
        blank=True,
        help_text=_("Pattern to search. "
                    "See https://docs.python.org/2/library/re.html#module-re")
    )

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.message = self.message.replace("\r\n", "\n")
        super(AutoCheckError, self).save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.message

    class Meta:
        app_label = 'server'
        verbose_name = _("Auto Check Error")
        verbose_name_plural = _("Auto Check Errors")
        permissions = (
            ("can_save_autocheckerror", "Can save Auto Check Error"),
        )

migasfree/server/models/device_feature.py
# -*- coding: utf-8 *-*

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from . import MigasLink


@python_2_unicode_compatible
class DeviceFeature(models.Model, MigasLink):
    name = models.CharField(
        verbose_name=_("name"),
        max_length=50,
        unique=True
    )

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'server'
        verbose_name = _("Feature")
        verbose_name_plural = _("Features")
        permissions = (("can_save_devicefeature", "Can save Device Feature"),)

migasfree/server/models/device_manufacturer.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from . import MigasLink


@python_2_unicode_compatible
class DeviceManufacturer(models.Model, MigasLink):
    name = models.CharField(
        verbose_name=_("name"),
        max_length=50,
        unique=True
    )

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'server'
        verbose_name = _("Manufacturer")
        verbose_name_plural = _("Manufacturers")
        permissions = (
            ("can_save_devicemanufacturer", "Can save Device Manufacturer"),
        )
        ordering = ['name']

migasfree/server/templates/includes/computer_messages_result.html
{% spaceless %}
{% load i18n %}

{% if query %}
    <div class="alert alert-info">{{ query|length }} {% trans 'results' %}</div>

    <table id="query" class="table table-striped table-hover table-condensed">
        <thead>
            <tr>
                <th>#</th>
                <th>{% trans 'Date' %}</th>
                <th>{% trans 'Computer' %}</th>
                <th>{% trans 'Project' %}</th>
                <th>{% trans 'IP' %}</th>
                <th>{% trans 'User' %}</th>
                <th>{% trans 'Message' %}</th>
            </tr>
        </thead>
        <tbody>
        {% for item in query %}
            <tr class="{% cycle '' 'even' %}">
                <td class="ordinal">{{ forloop.counter }}.</td>

                <td>{{ item.date|date:"Y-m-d H:i:s" }}</td>

                <td>
                    {% if item.delayed %}
                        <span class="fas fa-exclamation-triangle"></span>
                    {% else %}
                        <span class="fas fa-sync-alt fa-spin"></span>
                    {% endif %}
                    <a href="{% url 'admin:server_computer_change' item.computer_id %}">
                        {{ item.computer_name }} (CID-{{ item.computer_id }})
                    </a>
                </td>

                <td>{{ item.project }}</td>

                <td>{{ item.ip_address }}</td>

                <td>
                    <a href="{% url 'admin:server_user_change' item.user_id %}">
                        {{ item.user_name }} ({{ item.user_fullname }})
                    </a>
                </td>

                <td>{{ item.text }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="alert alert-warning">{% trans 'No messages to show' %}</div>
{% endif %}
{% endspaceless %}

migasfree/server/templates/includes/config_menu.html
{% load i18n %}

<ul class="dropdown-menu">
    {% if perms.server.change_clientproperty %}
        <li><a href="{% url 'admin:server_clientproperty_changelist' %}">{% trans 'Formulas' %}</a></li>
    {% endif %}
    {% if perms.server.change_serverproperty %}
        <li><a href="{% url 'admin:server_serverproperty_changelist' %}">{% trans 'Tag Categories' %}</a></li>
    {% endif %}
    {% if perms.server.change_attributeset %}
        <li><a href="{% url 'admin:server_attributeset_changelist' %}">{% trans 'Attribute Sets' %}</a></li>
    {% endif %}

    <li role="presentation" class="divider"></li>

    {% if perms.server.change_faultdefinition %}
        <li><a href="{% url 'admin:server_faultdefinition_changelist' %}?enabled__exact=1">{% trans 'Fault Definitions' %}</a></li>
    {% endif %}
    {% if perms.server.change_autocheckerror %}
        <li><a href="{% url 'admin:server_autocheckerror_changelist' %}">{% trans 'Auto Check Errors' %}</a></li>
    {% endif %}
    {% if perms.server.change_query %}
        <li><a href="{% url 'admin:server_query_changelist' %}">{% trans 'Queries' %}</a></li>
    {% endif %}

    <li role="presentation" class="divider"></li>

    {% if perms.server.change_project %}
    <li><a href="{% url 'admin:server_project_changelist' %}">{% trans 'Projects' %}</a></li>
    {% endif %}
    {% if perms.server.change_pms %}
    <li><a href="{% url 'admin:server_pms_changelist' %}">{% trans 'Package Management Systems' %}</a></li>
    {% endif %}
    {% if perms.server.change_platform %}
    <li><a href="{% url 'admin:server_platform_changelist' %}">{% trans 'Platforms' %}</a></li>
    {% endif %}

    <li role="presentation" class="divider"></li>

    {% if perms.server.change_userprofile %}
        <li><a href="{% url 'admin:server_userprofile_changelist' %}">{% trans 'User Profiles' %}</a></li>
    {% endif %}
    {% if perms.auth.change_group %}
        <li><a href="{% url 'admin:auth_group_changelist' %}">{% trans 'Groups' %}</a></li>
    {% endif %}
    {% if perms.server.change_domain %}
        <li><a href="{% url 'admin:server_domain_changelist' %}">{% trans 'Domains' %}</a></li>
    {% endif %}
    {% if perms.server.change_scope %}
        <li><a href="{% url 'admin:server_scope_changelist' %}">{% trans 'Scopes' %}</a></li>
    {% endif %}
    {% if user.is_superuser %}
        <li role="presentation" class="divider"></li>
        <li><a href="{% url 'admin:index' %}">{% trans 'Site administration' %}</a></li>
    {% endif %}
</ul>

migasfree/server/templates/includes/custom_form.html
{% if form.non_field_errors %}
    <div class="form_errors">
        {% for err in form.non_field_errors %}
            <div class="alert alert-danger">{{ err }}</div>
        {% endfor %}
    </div>
{% endif %}

{% for hidden in form.hidden_fields %}
   {{ hidden }}
{% endfor %}

{% for field in form.visible_fields %}
    {% if field.errors %}
        <div class="control-group has-error">
            <label class="control-label">{{ field.label }}</label>
            <div class="controls">{{ field }}
                <span class="help-inline">
                    {% for error in field.errors %}{{ error }}{% endfor %}
                </span>
            </div>
        </div>
    {% else %}
        <div class="control-group">
            <label class="control-label">{{ field.label }}</label>
            <div class="controls">{{ field }}
                {% if field.help_text %}
                    <p class="help-inline"><small>{{ field.help_text }}</small></p>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endfor %}

migasfree/server/templates/includes/deployment_timeline.html
{% load i18n %}
{% spaceless %}
{% if original.timeline or timeline %}
    <div class="btn-group btn-group-xs nowrap">
        <span class="timeline progress"
              title="{% if original.timeline %}{{ original.timeline.info }}{% else %}{{ timeline.info }}{% endif %}">
            <span class="progress-bar progress-bar-success" role="progressbar"
                  aria-valuenow="{% if original.timeline %}{{ original.timeline.percent }}{% else %}{{ timeline.percent }}{% endif %}"
                  aria-valuemin="0" aria-valuemax="100"
                  style="width: {% if original.timeline %}{{ original.timeline.percent }}{% else %}{{ timeline.percent }}{% endif %}%">
                <span>{% if original.timeline %}{{ original.timeline.percent }}{% else %}{{ timeline.percent }}{% endif %}%</span>
                <span class="sr-only">
                    {% if original.timeline %}
                        {% blocktrans with percent=original.timeline.percent %}{{ percent }}% completed{% endblocktrans %}
                    {% else %}
                        {% blocktrans with percent=timeline.percent %}{{ percent }}% completed{% endblocktrans %}
                    {% endif %}
                </span>
            </span>
        </span>

        <button type="button" class="btn btn-default btn-timeline dropdown-toggle" data-toggle="dropdown"
                data-deployment="{% if original.timeline %}{{ original.timeline.deployment_id }}{% else %}{{ timeline.deployment_id }}{% endif %}"
                aria-haspopup="true" aria-expanded="false">
            <span class="caret"> </span>
            <span class="sr-only">{% trans 'Toggle Dropdown' %}</span>
        </button>

        <ul class="dropdown-menu" role="menu">
            <li class="text-center"><span class="fas fa-sync-alt fa-spin"></span></li>
        </ul>
    </div>
{% endif %}
{% endspaceless %}

migasfree/server/templates/includes/devices_menu.html
{% load i18n %}

<ul id="devices" class="dropdown-menu">
    {% if perms.server.change_devicemanufacturer %}
        <li><a href="{% url 'admin:server_devicemanufacturer_changelist' %}">{% trans 'Manufacturers' %}</a></li>
    {% endif %}
    {% if perms.server.change_devicemodel %}
        <li><a href="{% url 'device_models_summary' %}">{% trans 'Models' %}</a></li>
    {% endif %}
    {% if perms.server.change_devicefeature %}
        <li><a href="{% url 'admin:server_devicefeature_changelist' %}">{% trans 'Features' %}</a></li>
    {% endif %}
    {% if perms.server.change_device %}
        <li><a href="{% url 'devices_summary' %}">{% trans 'Devices' %}</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="{% url 'device_replacement' %}">{% trans 'Devices Replacement' %}</a></li>
    {% endif %}
</ul>

migasfree/server/templates/includes/line_chart.html
{% load i18n admin_static %}

{% block extrahead %}
    <script src="{% static 'js/highcharts.js' %}" type="text/javascript"></script>
{% endblock extrahead %}

{% if chart %}
    <figure class="stat-container">
        <object type="image/svg+xml" data="{{ chart|safe }}"></object>
    </figure>
{% endif %}

{% if data %}
    <div id="container" class="stat-container"></div>
{% endif %}

{% block extrabody %}
    {% include 'includes/spline_js.html' with x_labels=x_labels data=data id='container' %}
{% endblock extrabody %}

migasfree/server/templates/includes/migas_link_menu.html
{% load i18n %}
{% if lnk.related %}
    {% for item in lnk.related %}
        <li>
            <p>
                <a class="nounderline" href="{{ item.url }}">
                    <span  class="label label-{% if item.count > 0 %}primary{% else %}default{% endif %}">{{item.count}}</span>
                </a>
                {{ item.text }}
                {% if item.actions %}
                        {% for action in item.actions %}
                            <a  class="nounderline" href="{{ action.url }}" title="{{action.description}}">
                                 <span class="label label-default">{{ action.title }}</span>
                            </a>
                        {% endfor %}
                {% endif %}
            </p>
        </li>
    {% endfor %}
{% endif %}

migasfree/server/templates/includes/multipie_chart.html
{% spaceless %}
{% load i18n %}

<div class="col-md-{{ col|default:4 }} col-sm-6 col-xs-12">
{% if item %}
    <div class="panel panel-default">
        <div class="panel-heading text-left lead">
            {{ item.title }}
            <div class="pull-right">
                <a href="{{ item.url|default:'#' }}"
                   class="label label-{{ label|default:'info' }}" title="{% trans 'Total' %}">
                    {{ item.total }}
                </a>
            </div>
        </div>
        <div class="panel-body">
            <div id="{{ id }}" class="highcharts"></div>
        </div>
    </div>
{% endif %}
</div>

{% endspaceless %}

migasfree/server/templates/includes/objects_link.html
{% if objects %}
    <ul>
    {% for item in objects %}
        <li>{{ item.link }}</li>
    {% endfor %}
    </ul>
{% endif %}

migasfree/server/templates/includes/parameters.html
{% load i18n %}

{% if form %}
    <form action="." method="post" class="controls" role="form">
        {% csrf_token %}
        <fieldset class="form-group input-group">
            <legend>{% trans 'Parameters' %}</legend>
            {% include 'includes/custom_form.html' %}
        </fieldset>

        <p><input type="submit" class="btn btn-primary" value="{% trans 'Submit' %}" /></p>
    </form>
{% endif %}