migasfree/server/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.views.generic import RedirectView, TemplateView
from django.urls import reverse_lazy
from django.conf import settings

from .views import *

public_patterns = [
    url(r'repository-url-template/', RepositoriesUrlTemplateView.as_view()),  # valid until migasfree-client 4.16
    url(r'server/info/', ServerInfoView.as_view()),
]

urlpatterns = [
    url(r'^src/', get_source_file, name='get_source_file'),

    url(r'^accounts/login/$', login, name='login'),

    url(
        r'^$',
        TemplateView.as_view(template_name='welcome.html'),
        name='bootstrap'
    ),

    url(
        r'^favicon\.ico$',
        RedirectView.as_view(
            url='%simg/favicon.png' % settings.STATIC_URL
        ),
    ),

    url(r'^api/v1/public/', include(public_patterns)),

    url(r'^query/(?P<query_id>\d+)/$', get_query, name='query'),
    url(
        r'^computer/messages/$',
        computer_messages,
        name='computer_messages'
    ),

    url(r'^info/(.*)', info, name='package_info'),

    url(
        r'^computer/(?P<pk>\d+)/hardware/$',
        hardware_resume,
        name='hardware_resume'
    ),
    url(
        r'^hw-node/(?P<pk>\d+)/$',
        hardware_extract,
        name='hardware_extract'
    ),

    url(
        r'^admin/server/computer/change_status/$',
        computer_change_status,
        name='computer_change_status'
    ),

    url(
        r'^admin/server/computer/delete_selected/$',
        computer_delete_selected,
        name='computer_delete_selected'
    ),

    url(
        r'^admin/server/computer/(?P<pk>\d+)/delete/$',
        ComputerDelete.as_view(),
        name='computer_delete'
    ),

    url(
        r'^admin/server/platform/delete_selected/$',
        platform_delete_selected,
        name='platform_delete_selected'
    ),

    url(
        r'^admin/server/platform/(?P<pk>\d+)/delete/$',
        PlatformDelete.as_view(),
        name='platform_delete'
    ),

    url(
        r'^admin/server/project/(?P<pk>\d+)/delete/$',
        ProjectDelete.as_view(),
        name='project_delete'
    ),

    url(r'^api/$', api, name='api'),

    url(
        r'^get_projects/$',
        get_projects,
        name='get_projects'
    ),
    url(
        r'^get_computer_info/$',
        get_computer_info,
        name='get_computer_info'
    ),
    url(
        r'^computer/(?P<uuid>.+)/label/$',
        computer_label,
        name='computer_label',
    ),
    url(
        r'^get_key_repositories/$',
        get_key_repositories,
        name='get_key_repositories'
    ),
    url(
        r'^timeline/$',
        timeline,
        name='timeline',
    ),
    url(
        r'^connections_model/$',
        connections_model,
        name='connections_model'
    ),

    url(
        r'^computer/replacement/$',
        computer_replacement,
        name='computer_replacement'
    ),

    url(
        r'^computer/(?P<pk>\d+)/events/$',
        computer_events,
        name='computer_events',
    ),

    url(
        r'^computer/(?P<pk>\d+)/simulate/$',
        computer_simulate_sync,
        name='computer_simulate_sync',
    ),

    url(
        r'^link/$',
        link,
        name='link',
    ),

    url(
        r'^device/replacement/$',
        device_replacement,
        name='device_replacement'
    ),

    url(
        r'^computer_autocomplete/$',
        ComputerAutocomplete.as_view(),
        name='computer_autocomplete',
    ),

    url(
        r'^attribute_autocomplete/$',
        AttributeAutocomplete.as_view(),
        name='attribute_autocomplete',
    ),

    url(
        r'^device_autocomplete/$',
        DeviceAutocomplete.as_view(),
        name='device_autocomplete',
    ),

    url(
        r'^user_profile_autocomplete/$',
        UserProfileAutocomplete.as_view(),
        name='user_profile_autocomplete',
    ),

    url(
        r'^group_autocomplete/$',
        GroupAutocomplete.as_view(),
        name='group_autocomplete',
    ),

    url(
        r'^domain_autocomplete/$',
        DomainAutocomplete.as_view(),
        name='domain_autocomplete',
    ),

    url(
        r'^device_connection_autocomplete/$',
        DeviceConnectionAutocomplete.as_view(),
        name='device_connection_autocomplete',
    ),

    url(
        r'^device_model_autocomplete/$',
        DeviceModelAutocomplete.as_view(),
        name='device_model_autocomplete',
    ),

    url(
        r'^device_logical_autocomplete/$',
        DeviceLogicalAutocomplete.as_view(),
        name='device_logical_autocomplete',
    ),

    url(
        r'^domain/change/$',
        change_domain,
        name='change_domain'
    ),

    url(
        r'^scope/change/$',
        change_scope,
        name='change_scope'
    ),

    # backwards compatibility
    url(
        r'^migasfree/$',
        RedirectView.as_view(url=reverse_lazy('bootstrap')),
    ),
    url(
        r'^migasfree/main/$',
        RedirectView.as_view(url=reverse_lazy('bootstrap')),
    ),
    url(r'^status/$', RedirectView.as_view(url=reverse_lazy('bootstrap')),),
    url(r'^migasfree/api/$', api),  # for 2.x clients
    url(
        r'^get_versions/$',
        RedirectView.as_view(url=reverse_lazy('get_projects'))
    ),
    url(
        r'^chart/version_computer/$',
        RedirectView.as_view(url=reverse_lazy('stats_dashboard'))
    ),
    url(
        r'^chart/synchronized_daily/$',
        RedirectView.as_view(url=reverse_lazy('stats_syncs_daily'))
    ),
    url(
        r'^chart/synchronized_monthly/$',
        RedirectView.as_view(url=reverse_lazy('stats_syncs_monthly'))
    ),
    url(
        r'^chart/delay_schedule/$',
        RedirectView.as_view(url=reverse_lazy('stats_project_schedule_delays'))
    ),
    url(
        r'^chart/delay_schedule/(?P<project_name>.+)/$',
        RedirectView.as_view(url=reverse_lazy('stats_project_schedule_delays'))
    ),
    url(
        r'^chart/dashboard/$',
        RedirectView.as_view(url=reverse_lazy('stats_dashboard'))
    ),
    url(
        r'^provided_computers/$',
        RedirectView.as_view(url=reverse_lazy('provided_computers'))
    ),
    url(
        r'^computer_label/$',
        computer_label
    ),
]

migasfree/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.i18n import JavaScriptCatalog

from ajax_select import urls as ajax_select_urls
from rest_framework.authtoken import views
from rest_framework.documentation import include_docs_urls
from rest_framework_swagger.views import get_swagger_view

from server.routers import router, device_router
from catalog.routers import router as catalog_router
from stats.routers import router as stats_router

from django.contrib import admin
admin.autodiscover()

TITLE = 'Migasfree REST API'

swagger_schema_view = get_swagger_view(title=TITLE)

urlpatterns = [
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^docs/', swagger_schema_view, name='docs'),
    url(r'^api-docs/', include_docs_urls(title=TITLE)),
    url(r'^token-auth/$', views.obtain_auth_token),
    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^api/v1/token/', include(router.urls)),
    url(r'^api/v1/token/', include(stats_router.urls)),
    url(r'^api/v1/token/devices/', include(device_router.urls)),
    url(r'^api/v1/token/catalog/', include(catalog_router.urls)),

    url(r'', include('migasfree.server.urls')),
    url(r'', include('migasfree.stats.urls')),

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^markdownx/', include('markdownx.urls')),

    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

if settings.DEBUG:
    try:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns
    except ImportError:
        pass

    if settings.STATIC_ROOT is not None:
        urlpatterns += static(
            settings.STATIC_URL,
            document_root=settings.STATIC_ROOT
        )

    if settings.MEDIA_ROOT is not None:
        urlpatterns += static(
            settings.MEDIA_URL,
            document_root=settings.MEDIA_ROOT,
            show_indexes=True
        )

migasfree/server/models/autocheck_error.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class AutoCheckError(models.Model):
    """
    This model is used to autocheck the errors and marked as 'checked' when they
    are introducing in the system. Sometimes the Package Management System, in
    the clients, return an error when really it is only a warning.
    The origin of this problem is that the package is poorly packaged.
    """
    message = models.TextField(
        verbose_name=_("message"),
        null=True,
        blank=True,
        help_text=_("Pattern to search. "
                    "See https://docs.python.org/2/library/re.html#module-re")
    )

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.message = self.message.replace("\r\n", "\n")
        super(AutoCheckError, self).save(force_insert, force_update, using, update_fields)

    def __str__(self):
        return self.message

    class Meta:
        app_label = 'server'
        verbose_name = _("Auto Check Error")
        verbose_name_plural = _("Auto Check Errors")
        permissions = (
            ("can_save_autocheckerror", "Can save Auto Check Error"),
        )

migasfree/server/models/device.py
# -*- coding: utf-8 -*-

import json

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext, ugettext_lazy as _

from . import DeviceConnection, DeviceModel, Attribute, MigasLink

from ..utils import (
    swap_m2m,
    remove_empty_elements_from_dict
)


class DeviceManager(models.Manager):
    def scope(self, user):
        qs = super(DeviceManager, self).get_queryset()
        if not user.is_view_all():
            qs = qs.filter(
                devicelogical__attributes__in=user.get_attributes()
            ).distinct()

        return qs


@python_2_unicode_compatible
class Device(models.Model, MigasLink):
    name = models.CharField(
        verbose_name=_("name"),
        max_length=50,
        unique=True
    )

    model = models.ForeignKey(
        DeviceModel,
        on_delete=models.CASCADE,
        verbose_name=_("model")
    )

    connection = models.ForeignKey(
        DeviceConnection,
        on_delete=models.CASCADE,
        verbose_name=_("connection")
    )

    available_for_attributes = models.ManyToManyField(
        Attribute,
        blank=True,
        verbose_name=_("available for attributes")
    )

    data = models.TextField(
        verbose_name=_("data"),
        null=True,
        default="{}"
    )

    objects = DeviceManager()

    def menu_link(self, request):
        if self.id:
            data = json.loads(self.data)
            ip = data.get('IP', None)
            if ip:
                address = 'http://{}'.format(ip)
            else:
                try:
                    address = 'http://{}:631'.format(
                        self.devicelogical_set.all()[0].attributes.all()[0].ip
                    )
                except:
                    address = ''

            if address:
                self._actions = [
                    [ugettext('HTTP'), address, _('web access to the device')]
                ]

        return super(Device, self).menu_link(request)

    def location(self):
        data = json.loads(self.data)
        return data.get('LOCATION', '')

    def as_dict(self):
        return {
            'name': self.name,
            'model': self.model.name,
            self.connection.name: json.loads(self.data),
        }

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        data = json.loads(self.data)
        if 'NAME' in data:
            data['NAME'] = data['NAME'].replace(' ', '_')
            self.data = json.dumps(data)

        super(Device, self).save(force_insert, force_update, using, update_fields)

    def incompatible_features(self, target):
        features = []
        for x in self.logical_devices_allocated():
            if target.devicelogical_set.filter(feature=x.feature).count() == 0:
                features.append(str(x.feature))

        for x in target.logical_devices_allocated():
            if self.devicelogical_set.filter(feature=x.feature).count() == 0:
                features.append(str(x.feature))

        return features

    def common_features_allocated(self, target):
        features = []
        for x in self.logical_devices_allocated():
            if target.devicelogical_set.filter(feature=x.feature).count() > 0:
                features.append(x.feature)

        for x in target.logical_devices_allocated():
            if self.devicelogical_set.filter(feature=x.feature).count() > 0:
                if x.feature not in features:
                    features.append(x.feature)

        return features

    def logical_devices_allocated(self):
        return self.devicelogical_set.exclude(attributes=None)

    @staticmethod
    def replacement(source, target):
        # Moves computers from logical device
        for feature in source.common_features_allocated(target):
            swap_m2m(
                source.devicelogical_set.get(feature=feature).attributes,
                target.devicelogical_set.get(feature=feature).attributes
            )

    def get_replacement_info(self):
        return remove_empty_elements_from_dict({
            ugettext("Device"): u'{} - {}'.format(self.link(), self.location()),
            ugettext("Logical devices"): '<br />' +
            '<br />'.join(
                str(x.feature) + ': ' + ', '.join(
                    c.link() for c in x.attributes.all()
                )
                for x in self.devicelogical_set.order_by('feature')
            ),
        })

    def related_objects(self, model, user):
        """
        Return Queryset with the related computers based in devicelogical_attributes
        """
        from migasfree.server.models import Computer, Attribute
        if model == 'computer':

            return Computer.productive.scope(user).filter(
                sync_attributes__in=Attribute.objects.filter(devicelogical__device__id=self.id)
            ).distinct()

        return None

    class Meta:
        app_label = 'server'
        verbose_name = _("Device")
        verbose_name_plural = _("Devices")
        unique_together = (("connection", "name"),)
        permissions = (("can_save_device", "Can save Device"),)

migasfree/server/models/device_connection.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from . import DeviceType, MigasLink


@python_2_unicode_compatible
class DeviceConnection(models.Model, MigasLink):
    name = models.CharField(
        verbose_name=_("name"),
        max_length=50
    )

    fields = models.CharField(
        verbose_name=_("fields"),
        max_length=100,
        null=True,
        blank=True,
        help_text=_("Fields separated by comma")
    )

    device_type = models.ForeignKey(
        DeviceType,
        on_delete=models.CASCADE,
        verbose_name=_("device type")
    )

    def __str__(self):
        return self.name

    class Meta:
        app_label = 'server'
        verbose_name = _("Connection")
        verbose_name_plural = _("Connections")
        unique_together = (("device_type", "name"),)
        permissions = (
            ("can_save_deviceconnection", "Can save Device Connection"),
        )

migasfree/server/models/device_model.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible

from . import DeviceType, DeviceManufacturer, DeviceConnection, MigasLink


@python_2_unicode_compatible
class DeviceModel(models.Model, MigasLink):
    name = models.CharField(
        verbose_name=_("name"),
        max_length=50,
        null=True,
        blank=True
    )

    manufacturer = models.ForeignKey(
        DeviceManufacturer,
        on_delete=models.CASCADE,
        verbose_name=_("manufacturer")
    )

    device_type = models.ForeignKey(
        DeviceType,
        on_delete=models.CASCADE,
        verbose_name=_("type")
    )

    connections = models.ManyToManyField(
        DeviceConnection,
        blank=True,
        verbose_name=_("connections")
    )

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        self.name = self.name.replace(" ", "_")
        super(DeviceModel, self).save(force_insert, force_update, using, update_fields)

    class Meta:
        app_label = 'server'
        verbose_name = _("Model")
        verbose_name_plural = _("Models")
        unique_together = (("device_type", "manufacturer", "name"),)
        permissions = (("can_save_devicemodel", "Can save Device Model"),)
        ordering = ['manufacturer', 'name']

migasfree/server/templates/base_full.html
{% extends "base.html" %}

{% block bodyclass %}full{% endblock bodyclass %}

migasfree/server/templates/computer_hardware_resume.html
{% extends "base.html" %}
{% load i18n mac_address_list %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li>{% trans 'Datum' %}</li>
        <li><a href="{% url 'admin:server_computer_changelist' %}">{% trans 'Computers' %}</a></li>
        <li><a href="{% url 'admin:server_computer_change' computer.id %}">{{ computer }}</a></li>
        <li>{% trans 'Hardware Information' %}</li>
    </ol>
{% endblock breadcrumbs %}

{% block content_title %}
    <h1>{% trans 'Hardware Information' %}: {{ computer.link }} </h1>

    <div class="row">
        <div class="col-md-6 col-xs-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-4 col-xs-4" title="{% if computer.machine == 'P' %}{% trans 'Physical' %}{% elif computer.is_docker %}docker{% else %}{% trans 'Virtual' %}{% endif %}">
                            <span class="pull-left {% if computer.machine == 'P' %}fas fa-laptop{% elif computer.is_docker %}fab fa-docker{% else %}fas fa-cube{% endif %} fa-4x"></span>
                            {% if computer.get_architecture %}
                                <span class="badge">{{ computer.get_architecture }} bits</span>
                            {% endif %}
                        </div>
                        <div class="col-md-8 col-xs-8">
                            <p>{{ computer.hwnode_set.first }}</p>
                            <p title="{% trans 'UUID' %}">{{ computer.uuid }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-xs-6">
                            <p title="{% trans 'CPU' %}">
                                <span class="fas fa-tachometer-alt fa-lg"></span>
                                {{ computer.cpu }}
                            </p>
                        </div>
                        <div class="col-md-6 col-xs-6">
                            <p title="{% trans 'RAM' %}">
                                <span class="fas fa-microchip fa-lg"></span>
                                {{ computer.ram|filesizeformat }}
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-xs-6">
                            <p title="{% trans 'Storage' %}">
                                <span class="far fa-hdd fa-lg"></span>
                                {{ computer.storage|filesizeformat }}
                                <span title="{% trans 'Disks' %}">({{ computer.disks }})</span>
                            </p>
                        </div>
                        <div class="col-md-6 col-xs-6">
                            <p title="{% trans 'MAC address' %}">
                                <span class="fas fa-exchange-alt fa-lg" data-fa-transform="rotate--90"></span>
                                {{ computer.mac_address|mac_address_list }}
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-xs-6">
                            <p title="{% trans 'last hardware capture' %}">
                                <span class="far fa-clock fa-lg"></span> {{ computer.last_hardware_capture }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content_title %}

{% block content %}
    <div class="container-fluid">
        {% for item in data %}
        <div class="row">
            <div class="col-xs-6 col-md-4 col-md-offset-{{ item.fields.level }}">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h2 class="panel-title">
                            <a href="{% url 'hardware_extract' item.pk %}">
                                {{ item.fields.description }}{% if item.fields.product %}: {{ item.fields.product }}{% endif %}
                            </a>
                        </h2>
                    </div>
                    <div class="panel-body">
                        <p>
                        {% for field, value in item.fields.items %}
                            {% if value and field != 'parent' and field != 'claimed' and field != 'computer' and field != 'product' and field != 'description' and field != 'level' and field != 'icon' and field != 'physid' %}
                                {{ field|capfirst }}:
                                {% if field == 'size' or field == 'capacity' %}
                                    {{ value|filesizeformat }}
                                {% else %}
                                    {{ value }}
                                {% endif %}
                                <br />
                            {% endif %}
                        {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

migasfree/server/templates/computer_label.html
<!doctype>
{% load admin_static %}
{% load i18n %}
<html>
    <head>
        <title>{{ search }}</title>
        <style type="text/css">
        body {
            width: 35em;
            height: 10em;
            border: 1px solid #000;
            padding: .5em 1em;
        }
        h1 {
            margin: 0 .5em;
            text-align: right;
            background: url('{% static 'img/favicon.png' %}') left center no-repeat;
        }
        h2 {
            font-size: 100%;
            text-align: center;
        }
        p {
            border-top: 1px solid #000;
            text-align: center;
        }
        </style>
    </head>
    <body>
        <h1>{{ search }}</h1>
        <h2>{{ uuid }}</h2>
        <h2>{% trans 'Server' %}: {{ server }}</h2>
        <p>{{ helpdesk }}</p>
    </body>
</html>

migasfree/server/templates/computer_replacement.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>{% trans 'Datum' %}</li>
        <li><a href="{% url 'computer_replacement' %}">{% trans 'Computers Replacement' %}</a></li>
    </ul>
{% endblock %}

{% block content %}
    <p class="lead">{% trans 'This procedure changes status, tags and devices between two computers.' %}</p>

    <form action="." method="post" class="controls" role="form">
        {% csrf_token %}
        {% include 'includes/custom_form.html' %}

        <p><input type="submit" class="btn btn-primary" value="{% trans 'Replace' %}" /></p>
    </form>

    {{ form.media }}
{% endblock content %}

migasfree/server/templates/device_models_summary.html
{% extends "base.html" %}
{% load i18n admin_static %}

{% block extrahead %}
    <script src="{% static 'js/highcharts.js' %}" type="text/javascript"></script>
{% endblock extrahead %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>{% trans 'Devices' %}</li>
        <li>{{ title }}</li>
    </ul>
{% endblock %}

{% block content_title %}
    {% if title %}<h1 class="change-list-title pull-left">{{ title }}</h1>{% endif %}

    {% if perms.server.add_devicemodel %}
        <div id="add-button" class="pull-left">
            <a role="button" href="{% url 'admin:server_devicemodel_add' %}" class="btn btn-primary"
               title="{% trans 'Add Model' %}">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </div>
    {% endif %}
{% endblock content_title %}

{% block content %}
    {% include 'includes/search_form.html' with url_name='admin:server_devicemodel_changelist' %}

    <div class="row text-center">
        {% include 'includes/multipie_chart.html' with item=models_by_manufacturer id='models-manufacturer' col=6 %}
    </div>
{% endblock content %}

{% block extrabody %}
    <script type="text/javascript" src="{% static 'js/chart_config.js' %}"></script>

    <script type="text/javascript">
    Highcharts.setOptions({
        lang: {
            noData: '{{ chart_options.no_data }}',
            resetZoom: '{{ chart_options.reset_zoom }}'
        }
    });

    var modelsManufacturer = {{ models_by_manufacturer.data|safe }};
    var modelsManufacturerOptions = {
        chart: {
            renderTo: 'models-manufacturer'
        },
        series: [{
            data: loadDatum(modelsManufacturer)
        }]
    };
    modelsManufacturerOptions = jQuery.extend(true, {}, options, modelsManufacturerOptions);
    var modelsManufacturerChart = new Highcharts.Chart(modelsManufacturerOptions);
    </script>
{% endblock extrabody %}

migasfree/server/templates/device_replacement.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>{% trans 'Devices' %}</li>
        <li><a href="{% url 'device_replacement' %}">{% trans 'Devices Replacement' %}</a></li>
    </ul>
{% endblock %}

{% block content %}
    <p>{% trans 'This procedure replaces two devices.' %}</p>

    <form action="." method="post" class="controls" role="form">
        {% csrf_token %}
        {% include 'includes/custom_form.html' %}

        <p><input type="submit" class="btn btn-primary" value="{% trans 'Replace' %}" /></p>
    </form>

    {{ form.media }}
{% endblock content %}

migasfree/server/templates/devices_summary.html
{% extends "base.html" %}
{% load i18n admin_static %}

{% block extrahead %}
    <script src="{% static 'js/highcharts.js' %}" type="text/javascript"></script>
{% endblock extrahead %}

{% block breadcrumbs %}
    <ul class="breadcrumb">
        <li>{% trans 'Devices' %}</li>
        <li>{{ title }}</li>
    </ul>
{% endblock %}

{% block content_title %}
    {% if title %}<h1 class="change-list-title pull-left">{{ title }}</h1>{% endif %}

    {% if perms.server.add_device %}
        <div id="add-button" class="pull-left">
            <a role="button" href="{% url 'admin:server_device_add' %}" class="btn btn-primary"
               title="{% trans 'Add Device' %}">
                <span class="glyphicon glyphicon-plus"></span>
            </a>
        </div>
    {% endif %}
{% endblock content_title %}

{% block content %}
    {% include 'includes/search_form.html' with url_name='admin:server_device_changelist' %}

    <div class="row text-center">
        {% include 'includes/multipie_chart.html' with item=devices_by_connection id='devices-connection' %}

        {% include 'includes/multipie_chart.html' with item=devices_by_model id='devices-model' %}

        {% include 'includes/multipie_chart.html' with item=devices_by_manufacturer id='devices-manufacturer' %}
    </div>
{% endblock content %}

{% block extrabody %}
    <script type="text/javascript" src="{% static 'js/chart_config.js' %}"></script>

    <script type="text/javascript">
    Highcharts.setOptions({
        lang: {
            noData: '{{ chart_options.no_data }}',
            resetZoom: '{{ chart_options.reset_zoom }}'
        }
    });

    var devicesConnection = {{ devices_by_connection.data|safe }};
    var devicesConnectionOptions = {
        chart: {
            renderTo: 'devices-connection'
        },
        series: [{
            data: loadDatum(devicesConnection)
        }]
    };
    devicesConnectionOptions = jQuery.extend(true, {}, options, devicesConnectionOptions);
    var devicesConnectionChart = new Highcharts.Chart(devicesConnectionOptions);

    var devicesModel = {{ devices_by_model.data|safe }};
    var devicesModelOptions = {
        chart: {
            renderTo: 'devices-model'
        },
        series: [{
            data: loadDatum(devicesModel)
        }]
    };
    devicesModelOptions = jQuery.extend(true, {}, options, devicesModelOptions);
    var devicesModelChart = new Highcharts.Chart(devicesModelOptions);

    var devicesManufacturer = {{ devices_by_manufacturer.data|safe }};
    var devicesManufacturerOptions = {
        chart: {
            renderTo: 'devices-manufacturer'
        },
        series: [{
            data: loadDatum(devicesManufacturer)
        }]
    };
    devicesManufacturerOptions = jQuery.extend(true, {}, options, devicesManufacturerOptions);
    var devicesManufacturerChart = new Highcharts.Chart(devicesManufacturerOptions);
    </script>
{% endblock extrabody %}

migasfree/server/templates/platform_confirm_delete_selected.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Delete selected platforms' %}{% endblock %}

{% block breadcrumbs %}
    <ol class="breadcrumb">
        <li>{% trans 'Config' %}</li>
        <li><a href="{% url 'admin:server_platform_changelist' %}">{% trans 'Platforms' %}</a></li>
    </ol>
{% endblock breadcrumbs %}

{% block content %}
    <h1 class="">{% trans 'Are you sure?' %}</h1>

    <form action="{% url 'platform_delete_selected' %}" method="post">
        {% csrf_token %}
        <p>{% trans 'Are you sure you want to delete these platforms?' %} {{ object_list }}</p>
        <input type="hidden" name="selected" value="{{ object_list }}" />
        <div class="form-actions">
            <button class="btn btn-large btn-danger" type="submit">{% trans "Yes, I'm sure" %}</button> {% trans 'or' %}
            <a href="{% url 'admin:server_platform_changelist' %}" class="btn btn-default">{% trans 'cancel' %}</a>
        </div>
    </form>
{% endblock %}